### ISSUE TITLE
ci: `tree-editor` template fails CI

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/generator-theia-extension#138]
**Description**

The `tree-editor` template has been failing for some time now in CI resulting in a failed build:
- https://github.com/eclipse-theia/generator-theia-extension/runs/5787095655?check_suite_focus=true#step:5:2732

```
Error: tree-editor: src/browser/example-file/example-file-command.ts(49,78): error TS2345: Argument of type 'URI' is not assignable to parameter of type 'FileStat'.
tree-editor:   Type 'URI' is missing the following properties from type 'FileStat': isFile, isDirectory, isSymbolicLink, resource, name
```

From what I can tell it has been failing since 16 days ago: https://github.com/eclipse-theia/generator-theia-extension/runs/5578246651?check_suite_focus=true#step:5:2756.

cc @JonasHelming

**Comment by vince-fugnitto** [comment]
The breaking change comes from https://github.com/eclipse-theia/theia/pull/10767.

**Comment by JonasHelming** [comment]
@vince-fugnitto : comment on this: I discovered that the build failure notifications were unfortunately filtered out on my side. I changed this to be able to react earlier next time

**Comment by vince-fugnitto** [comment]
@JonasHelming there are certain conditions to when the notifications are sent and to whom:

- https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

I assume if you always want notifications you might be interested in modifying the workflow to notify you by email or slack in all cases when a failure occurs.

**Comment by JonasHelming** [comment]
Yes, but the regular notifcations are actually working, I fixed this on my end.

**Comment by lucas-koehler** [comment]
I'll investigate this today or tomorrow.

**Comment by JonasHelming** [comment]
@vince-fugnitto I just realized, we never released this. Can we do a release (maybe after Theia is done)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I just realized, we never released this. Can we do a release (maybe after Theia is done)

@JonasHelming it should be released :)
